------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">✍ EJERCICIOS NUMPY PARA @EGGERS</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [1]:
import numpy as np

1. Crea un vector entre 7 y 66.

In [5]:
arr1 = np.arange(7,67, dtype=int)
arr1

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66])

2. Invierte el vector generado anteriormente.


In [7]:
arr1[::-1]

array([66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7])

In [10]:
arr2 = np.arange(67,7, -1, dtype=int)
arr2

array([67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51,
       50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8])

3. Matriz de 4x4 con valores entre 0 y 15.

In [13]:
np.arange(0,16, dtype = int).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

5. Crea la matriz identidad de 5x5.

In [14]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

6. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.

In [22]:
matrizMarco = np.ones((5,5))
matrizMarco[1,1:4] = matrizMarco[3,1:4] = 0
matrizMarco[2,1] =matrizMarco[2,3] = 0
matrizMarco

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

7. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.

In [29]:
matriz7 = np.zeros((4,4), dtype=int)

for i in range(4):
  matriz7[i] = np.linspace(3,0,4, dtype=int)

matriz7

array([[3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0]])

8. Crea un array de ceros de 2x7.

In [30]:
np.zeros((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

9. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.

In [41]:
matriz9 = (np.zeros((5,4)))
matriz9[0] = 1
matriz9

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

10. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

In [47]:
lineaPar = np.array([0,1,0,1,0,1,0,1], dtype = int)
lineaInpar = np.array([1,0,1,0,1,0,1,0], dtype = int)

tablero = np.zeros((8,8), dtype=int)

for i in range(8):
  if (i % 2 == 0):
    tablero[i] = lineaPar
  else:
    tablero[i] = lineaInpar

tablero

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])